title = "att configs"
version = "1.0"

[id3v23]
ALBARTIST = "TPE2"
ALBUM = "TALB"
ARTIST = "TPE1"
TITLE = "TIT2"
DISCNUM = "TPOS"
TRACKNUM = "TRCK"
YEAR = "TYER"
GENRE = "TCON"
COMMENT = "COMM"

[vorbis]
ALBARTIST = "ALBUMARTIST"
ALBUM = "ALBUM"
ARTIST = "ARTIST"
TITLE = "TITLE"
DISCNUM = "DISCNUMBER"
TRACKNUM = "TRACKNUMBER"
YEAR = "DATE"
GENRE = "GENRE"
COMMENT = "COMMENT"

